web:
  image: rgardler/acs-logging-test-web:build2016
  ports:
    - "80:80"
  env_file:
    - ./env.conf

analyzer:
  image: rgardler/acs-logging-test-analyze:build2016
  env_file:
    - ./env.conf

rest_enqueue:
  image: rgardler/acs-logging-test-rest-enqueue:build2016
  ports:
    - "5000:5000"
  env_file:
    - ./env.conf
